/*
 * Copyright (c) 2019, AngBoot Technology Corp, All Rights Reserved.
 *
 * The software and information contained herein are copyrighted and
 * proprietary to AngBoot Technology Corp. This software is furnished
 * pursuant to a written license agreement and may be used, copied,
 * transmitted, and stored only in accordance with the terms of such
 * license and with the inclusion of the above copyright notice. Please
 * refer to the file "COPYRIGHT" for further copyright and licensing
 * information. This software and information or any other copies
 * thereof may not be provided or otherwise made available to any other
 * person.
 */

/*
 * This file is automatically generated. Do not edit this file directly. Modify the
 * index.components section of index.yaml instead
 * Run "ant angular.generate-index-files" in the build directory to update the generated
 * file.
 */

import { Type } from "@angular/core";
import { PortalTitleBarComponent } from "./portal-title-bar/portal-title-bar.component";
import { WelcomeComponent } from "./welcome/welcome.component";

export const MODULE_COMPONENTS: Type<any>[] = [
   PortalTitleBarComponent,
   WelcomeComponent
];
