/*
 * Copyright (c) 2019, AngBoot Technology Corp, All Rights Reserved.
 *
 * The software and information contained herein are copyrighted and
 * proprietary to AngBoot Technology Corp. This software is furnished
 * pursuant to a written license agreement and may be used, copied,
 * transmitted, and stored only in accordance with the terms of such
 * license and with the inclusion of the above copyright notice. Please
 * refer to the file "COPYRIGHT" for further copyright and licensing
 * information. This software and information or any other copies
 * thereof may not be provided or otherwise made available to any other
 * person.
 */

/*
 * This file is automatically generated. Do not edit this file directly. Modify the
 * index.directives section of index.yaml instead
 * Run "ant angular.generate-index-files" in the build directory to update the generated
 * file.
 */

import { Type } from "@angular/core";
import { ActionsContextmenuAnchorDirective } from "./fixed-dropdown/actions-contextmenu-anchor.directive";
import { BlockMouseDirective } from "./directive/block-mouse.directive";
import { ContextmenuDropdownAnchorDirective } from "./fixed-dropdown/contextmenu-dropdown-anchor.directive";
import { DefaultFocusDirective } from "./directive/default-focus.directive";
import { EnterClickDirective } from "./directive/enter-click.directive";
import { EnterSubmitDirective } from "./directive/enter-submit.directive";
import { ExpandStringDirective } from "./expand-string/expand-string.directive";
import { FixedDropdownDirective } from "./directive/fixed-dropdown.directive";
import { InputTrimDirective } from "./directive/input-trim.directive";
import { OutOfZoneDirective } from "./directive/out-of-zone.directive";
import { ResizableTableDirective } from "./directive/resizable-table.directive";
import { SelectionBoxDirective } from "./directive/selection-box.directive";
import { SortColumnDirective } from "./directive/sort-column.directive";
import { TooltipDirective } from "./tooltip/tooltip.directive";
import { TooltipIfDirective } from "./directive/tooltip-if.directive";
import { TouchScrollDirective } from "./directive/touch-scroll.directive";

export const MODULE_DIRECTIVES: Type<any>[] = [
   ActionsContextmenuAnchorDirective,
   BlockMouseDirective,
   ContextmenuDropdownAnchorDirective,
   DefaultFocusDirective,
   EnterClickDirective,
   EnterSubmitDirective,
   ExpandStringDirective,
   FixedDropdownDirective,
   InputTrimDirective,
   OutOfZoneDirective,
   ResizableTableDirective,
   SelectionBoxDirective,
   SortColumnDirective,
   TooltipDirective,
   TooltipIfDirective,
   TouchScrollDirective
];
